name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

env:
  GOEXPERIMENT: arenas
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.12.2

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-go@v6.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
